### ISSUE TITLE
(un)SelectAll() not working on mobile

### ISSUE THREAD

**Issue by Hoads** [HemantNegi/jquery.sumoselect#188]
Recently I upgraded to 3.0.3 (from 3.0.2) and since it seems the selectAll()/unSelectAll() function is not working on mobile anymore.
Tried to create a fiddle: https://jsfiddle.net/dpk5rLyy/2/

When I run this in chrome on Android and click on 'SelectAll' nothing is selected.
However when I tick the chrome option 'request desktop site' and I click on 'SelectAll' it says 4 options are selected.

In the toggAllSel function, if I replace: 
O.optDiv.find('li.opt:not(.hidden,.disabled)').each(function(ix,e)
for:
O.E.find('option').not(':disabled').each(function (ix, el)

It seems to work again. No idea if it will break something else, just trying to give as much info as possible.

**Comment by gavrochelegnou** [comment]
I confirm this.
When using "native" on mobile O.optDiv is not defined (code skipped)
Therefore when calling the find method on i later ...

**Comment by HemantNegi** [comment]
Thanks for pointing out.
Fixed now, Please verify .

**Comment by Hoads** [comment]
Works like a charm, thanks!

**Comment by zansimon** [comment]
Hi HemantNegi, 

I am having a similar issue and I downloaded the latest version 3.0.2. 

This only happens on mobile and it happens when I simulate mobile loads on Chrome using the developer tool.

My code is: 

`jQuery("select#cc-credit-card-properties")[0].sumo.selectItem("is_zero_interest_card");`

I get the error message:
```
    Uncaught TypeError: O.optDiv.find is not a function
    at Object.selAllState (custom-sumoselect.js?ver=180211-45622:270)
    at Object.toggSel (custom-sumoselect.js?ver=180211-45622:563)
    at Object.selectItem (custom-sumoselect.js?ver=180211-45622:664)
    at HTMLDocument.<anonymous> ((index):658)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
```
You can recreate the error yourself by visiting the page https://www.creditcardscompare.co.nz/interest-free-credit-cards/ on a mobile device or simulating mobile on chrome and click on the Filters link/icon

**Comment by sandeep111995** [comment]
This is working fine for me on mobile,

$('select.SlectBox').on('sumo:opened', function(sumo) {

				$(".select-all").click(function(){
					if ($(this).hasClass("selected")) {

						$(this).parents(".SumoSelect").find("select>option").prop("selected", true);

						$('select.SlectBox')[0].sumo.selectAll();
						$(this).parent().find("ul.options>li").addClass("selected");
					}
					else {

						$(this).parents(".SumoSelect").find("select>option").prop("selected", false);

						$('select.SlectBox')[0].sumo.unSelectAll();
						$(this).parent().find("ul.options>li").removeClass("selected");
					}
		    	});
			});

**Comment by d3stroyahh** [comment]
the issue is NOT solved.
Here's my fix. It works, now ALL of sumo multiselect will work when select all and unselect all on mobile WHEN use forcecustomrendering true.
`$('#mysumo').SumoSelect({
                    forceCustomRendering: true,
                    search: true, searchText: 'Search here...',
                    selectAll: true
                });
$("html").on('click', '.select-all', function(){
	var myObj = $(this).closest('.SumoSelect.open').children()[0];
	if ($(this).hasClass("selected")) {
		$(this).parents(".SumoSelect").find("select>option").prop("selected", true);
		$(myObj)[0].sumo.selectAll();
		$(this).parent().find("ul.options>li").addClass("selected");
	}
	else {
		$(this).parents(".SumoSelect").find("select>option").prop("selected", false);
		$(myObj)[0].sumo.unSelectAll();
		$(this).parent().find("ul.options>li").removeClass("selected");
	}
});`

**Comment by ZeeshanRS** [comment]
hello Buddy , i have a Issue , when i was loaded the 2nd MultiSelect Dropdown Using Jquery , Select All working in all browser but in Mozila FireFox its not working
![image](https://user-images.githubusercontent.com/102017817/169758931-3bd3f34d-8f06-46a7-8ea1-15f17b4099ab.png)


look at this its chrome working perfect but in 2nd image check my serious issue
![image](https://user-images.githubusercontent.com/102017817/169759217-650387f8-f2df-4ad0-83d5-d8466e70c3dd.png)


its Mozila FireFox
