### ISSUE TITLE
To hide the select box once we lost focus 

### ISSUE THREAD

**Issue by spradeeshraju** [HemantNegi/jquery.sumoselect#42]
Team,

             I see an issue like, if I have dropdown and a button in page, Once after the selection in the multiselect dropdown, I need to click the button twice, as the focus of the dropdown still there on first click. How can we solve it.

**Comment by JimmyClement** [comment]
I have same issue, once user clicks on SumoSelect select box, user should re-click on same sumoselect to close it, it doesn't close itself once user clicks on somewhere else on page.

**Comment by JimmyClement** [comment]
I fixed the code to solve this issue and made a pull request

**Comment by HemantNegi** [comment]
its fixed in next release.
Thanks for your interest.

**Comment by spradeeshraju** [comment]
Hi Jimmy, what was the fix made ?
Hemant, does that mean if I download the latest version, that will be solved ?

**Comment by JimmyClement** [comment]
You can just use my fork:
https://github.com/JimmyClement/jquery.sumoselect

**Comment by JimmyClement** [comment]
It was focusout event, see my fork: https://github.com/JimmyClement/jquery.sumoselect

**Comment by spradeeshraju** [comment]
no Jimmy, it gives issues. Atleast earlier if I click outside the dropdown, it hides and then I can click the button. Now after the code download, nothing happened. The dropdown remains open.

**Comment by JimmyClement** [comment]
Just add these to the JS:
https://github.com/JimmyClement/jquery.sumoselect/commit/a6a22ccc96f4b125963bd20e71b939457938f5c6

in events part. I don't know about you, but it simply works as I want for
me, you can wait for official "next release"

**Comment by munkyxtc** [comment]
@HemantNegi This issue still doesn't appear to be fixed using the latest development version in the repo.  I took the latest version from the development branch and dropped it into my program and the issue still persists for IE -- the blur event is called sporatically at best which causes the same issue reported in the original.

I took @JimmyClement's version that was based on 1.2 and dropped it in which appeared to work; however, simply adding the focusout event to the 2.0.2 version does not work.  I'd prefer to continue developing against the latest version but IE is a requirement for this project.  

For now, I'm working around it by just checking for IE on load and then forcing the OK/Cancel on every multiselect dropdown; however, this is a user annoyance IMO and not my desired implementation.  


![Here is what it looks like in IE (11) on the live demo site.  Also behaves this way with Dev version](https://cloud.githubusercontent.com/assets/1876769/7029057/73016fc6-dd28-11e4-8ba3-568a3631961f.png)

**Comment by HemantNegi** [comment]
Hi @munkyxtc,
 i have implemented 'blur' event to hide the dropdown, so that
 `$(document).on('click.sumo', function (e) {`
was no longer needed. 
yes i just came to know of this issue in ie version < 9
i think there is some issue with `blur` event.

anyways we can handle the situation by using  `$(document).on('click.sumo',` any time.

just let me see more workarounds!

**Comment by HemantNegi** [comment]
Hey,
i figured out that `blur` event is not triggered in ie properly. so i added `onfocusout`
`O.select.on('blur focusout', function () {`

and it started working with all versions of ie, when changed the version from dev tools of ie.
can you confirm this on your end!

Thanks.

**Comment by munkyxtc** [comment]
@HemantNegi I tried originally to just add the focusout behavior that jimmy posted about.  For his version of the plugin I was able to make it work; however, simply adding focusout to the 2.0.2 version the issue is not resolved; actually it makes the control not work correctly.  Whenever I click on an option the list quickly closes; however, it doesn't even record that I chose an item.

I'm doing a little more digging to see if I can help isolate it and will post my findings

**Comment by munkyxtc** [comment]
@HemantNegi I actually was able to make it work finally; however, I found another item.  If you have a dropdown with OK/Cancel enabled this dropdown closes the dropdown immediately and does not record the user selection.

Another item I noticed is that when focusout is set in the listener that the 2nd option in the list never allows selection.  Its the oddest thing.
